/**
 * Mock Test module — dummy payloads shaped for one-line API swaps.
 * ------------------------------------------------------------------
 * TODO: Replace each export with matching GET/POST responses.
 */

// TODO: Replace with GET /api/v1/tests
export const dummyTests = [
  {
    testId: 't-001',
    courseId: 'c-001',
    courseTitle: 'iC-38 Batch May 2025',
    title: 'Chapter 1 — IRDA Fundamentals',
    description: '25 questions covering the basics of IRDA regulations and insurance principles.',
    durationMinutes: 30,
    totalMarks: 25,
    passingMarks: 15,
    questionCount: 25,
    shuffleQuestions: true,
    allowReattempt: true,
    cooldownMinutes: 30,
    maxAttempts: null,
    availableFrom: '2025-05-01T00:00:00.000Z',
    availableUntil: '2025-07-31T23:59:59.000Z',
    attemptsUsed: 1,
    canAttempt: true,
    canAttemptReason: null,
    lastAttemptResult: {
      score: 18,
      percentage: 72.0,
      passed: true,
      submittedAt: '2025-05-08T10:20:00.000Z',
    },
  },
  {
    testId: 't-002',
    courseId: 'c-001',
    courseTitle: 'iC-38 Batch May 2025',
    title: 'Chapter 2 — Policy Types & Riders',
    description: '30 questions on life insurance policy types, riders, and premium structures.',
    durationMinutes: 35,
    totalMarks: 30,
    passingMarks: 18,
    questionCount: 30,
    shuffleQuestions: true,
    allowReattempt: true,
    cooldownMinutes: 30,
    maxAttempts: null,
    availableFrom: '2025-05-01T00:00:00.000Z',
    availableUntil: '2025-07-31T23:59:59.000Z',
    attemptsUsed: 1,
    canAttempt: false,
    canAttemptReason: 'Please wait until 3:45 PM to reattempt.',
    lastAttemptResult: {
      score: 17,
      percentage: 56.6,
      passed: false,
      submittedAt: '2025-05-07T15:00:00.000Z',
    },
  },
  {
    testId: 't-003',
    courseId: 'c-001',
    courseTitle: 'iC-38 Batch May 2025',
    title: 'Chapter 3 — Life Insurance Concepts',
    description: '25 questions on fundamental life insurance concepts and principles.',
    durationMinutes: 30,
    totalMarks: 25,
    passingMarks: 15,
    questionCount: 25,
    shuffleQuestions: true,
    allowReattempt: true,
    cooldownMinutes: 30,
    maxAttempts: null,
    availableFrom: '2025-05-01T00:00:00.000Z',
    availableUntil: '2025-07-31T23:59:59.000Z',
    attemptsUsed: 0,
    canAttempt: true,
    canAttemptReason: null,
    lastAttemptResult: null,
  },
];

// TODO: Replace with POST /api/v1/tests/:testId/attempts
export function createDummyAttempt(now = Date.now()) {
  return {
    attemptId: 'a-001',
    testId: 't-001',
    attemptNumber: 2,
    durationMinutes: 30,
    startedAt: new Date(now).toISOString(),
    expiresAt: new Date(now + 30 * 60 * 1000).toISOString(),
    questions: [
      {
        questionId: 'q-001',
        questionText: 'IRDAI stands for?',
        optionA: 'Insurance Regulatory and Development Authority of India',
        optionB: 'Indian Risk and Development Authority',
        optionC: 'Insurance Research and Data Authority of India',
        optionD: 'None of the above',
      },
      {
        questionId: 'q-002',
        questionText: 'What is the free-look period for a life insurance policy?',
        optionA: '7 days',
        optionB: '10 days',
        optionC: '15 days',
        optionD: '30 days',
      },
      {
        questionId: 'q-003',
        questionText: 'Which type of insurance provides coverage for a fixed period?',
        optionA: 'Whole life insurance',
        optionB: 'Term life insurance',
        optionC: 'Endowment plan',
        optionD: 'Money-back policy',
      },
      {
        questionId: 'q-004',
        questionText: 'The minimum age to become a LIC agent is?',
        optionA: '16 years',
        optionB: '18 years',
        optionC: '21 years',
        optionD: '25 years',
      },
      {
        questionId: 'q-005',
        questionText: 'ULIP stands for?',
        optionA: 'Unit Linked Insurance Plan',
        optionB: 'Universal Life Insurance Policy',
        optionC: 'Unified Life Income Plan',
        optionD: 'Unit Liability Insurance Plan',
      },
      {
        questionId: 'q-006',
        questionText: 'Which authority regulates insurance companies in India?',
        optionA: 'RBI',
        optionB: 'SEBI',
        optionC: 'IRDAI',
        optionD: 'AMFI',
      },
      {
        questionId: 'q-007',
        questionText: "What does 'sum assured' mean in a life insurance policy?",
        optionA: 'Total premium paid',
        optionB: 'Guaranteed amount paid on death or maturity',
        optionC: 'Bonus accumulated',
        optionD: 'Surrender value of policy',
      },
      {
        questionId: 'q-008',
        questionText: 'A money-back policy pays survival benefits at?',
        optionA: 'End of policy term only',
        optionB: 'Regular intervals during policy term',
        optionC: 'Only on death',
        optionD: 'Only after 10 years',
      },
      {
        questionId: 'q-009',
        questionText: 'What is a rider in an insurance policy?',
        optionA: 'A separate standalone policy',
        optionB: 'An add-on benefit attached to base policy',
        optionC: 'A type of premium discount',
        optionD: 'A claim settlement process',
      },
      {
        questionId: 'q-010',
        questionText: 'The iC-38 examination is conducted by?',
        optionA: 'LIC of India',
        optionB: 'IRDAI',
        optionC: 'Insurance Institute of India',
        optionD: 'Ministry of Finance',
      },
    ],
  };
}

/** @param {typeof dummyTests[number]} test */
export function createDummyAttemptForTest(test, now = Date.now()) {
  const base = createDummyAttempt(now);
  return {
    ...base,
    testId: test.testId,
    durationMinutes: test.durationMinutes,
    attemptNumber: test.attemptsUsed + 1,
    expiresAt: new Date(now + test.durationMinutes * 60 * 1000).toISOString(),
  };
}

/** Reference answer key only — aligns with POST attempt + GET result flow. */
// TODO: Replace with GET /api/v1/attempts/:attemptId/result (or server scoring)
export const dummyResult = {
  attemptId: 'a-001',
  testTitle: 'Chapter 1 — IRDA Fundamentals',
  attemptNumber: 2,
  score: 8,
  totalMarks: 10,
  percentage: 80.0,
  passed: true,
  passingMarks: 6,
  timeTakenSeconds: 845,
  submittedAt: new Date().toISOString(),
  questions: [
    {
      questionId: 'q-001',
      questionText: 'IRDAI stands for?',
      optionA: 'Insurance Regulatory and Development Authority of India',
      optionB: 'Indian Risk and Development Authority',
      optionC: 'Insurance Research and Data Authority of India',
      optionD: 'None of the above',
      correctOption: 'A',
      selectedOption: 'A',
      isCorrect: true,
      marksAwarded: 1,
      explanation:
        'IRDAI stands for Insurance Regulatory and Development Authority of India, established under the IRDAI Act 1999.',
    },
    {
      questionId: 'q-002',
      questionText: 'What is the free-look period for a life insurance policy?',
      optionA: '7 days',
      optionB: '10 days',
      optionC: '15 days',
      optionD: '30 days',
      correctOption: 'C',
      selectedOption: 'B',
      isCorrect: false,
      marksAwarded: 0,
      explanation:
        'As per IRDAI guidelines, the free-look period is 15 days from receipt of the policy document.',
    },
    {
      questionId: 'q-003',
      questionText: 'Which type of insurance provides coverage for a fixed period?',
      optionA: 'Whole life insurance',
      optionB: 'Term life insurance',
      optionC: 'Endowment plan',
      optionD: 'Money-back policy',
      correctOption: 'B',
      selectedOption: 'B',
      isCorrect: true,
      marksAwarded: 1,
      explanation: 'Term life insurance provides coverage for a specified period only.',
    },
    {
      questionId: 'q-004',
      questionText: 'The minimum age to become a LIC agent is?',
      optionA: '16 years',
      optionB: '18 years',
      optionC: '21 years',
      optionD: '25 years',
      correctOption: 'B',
      selectedOption: 'B',
      isCorrect: true,
      marksAwarded: 1,
      explanation: 'Minimum age requirement to become a LIC agent is 18 years.',
    },
    {
      questionId: 'q-005',
      questionText: 'ULIP stands for?',
      optionA: 'Unit Linked Insurance Plan',
      optionB: 'Universal Life Insurance Policy',
      optionC: 'Unified Life Income Plan',
      optionD: 'Unit Liability Insurance Plan',
      correctOption: 'A',
      selectedOption: 'C',
      isCorrect: false,
      marksAwarded: 0,
      explanation:
        'ULIP stands for Unit Linked Insurance Plan — combining investment and insurance.',
    },
    {
      questionId: 'q-006',
      questionText: 'Which authority regulates insurance companies in India?',
      optionA: 'RBI',
      optionB: 'SEBI',
      optionC: 'IRDAI',
      optionD: 'AMFI',
      correctOption: 'C',
      selectedOption: 'C',
      isCorrect: true,
      marksAwarded: 1,
      explanation: 'IRDAI is the regulatory authority for insurance companies in India.',
    },
    {
      questionId: 'q-007',
      questionText: "What does 'sum assured' mean?",
      optionA: 'Total premium paid',
      optionB: 'Guaranteed amount paid on death or maturity',
      optionC: 'Bonus accumulated',
      optionD: 'Surrender value',
      correctOption: 'B',
      selectedOption: 'B',
      isCorrect: true,
      marksAwarded: 1,
      explanation:
        'Sum assured is the guaranteed amount the insurer pays on death or policy maturity.',
    },
    {
      questionId: 'q-008',
      questionText: 'A money-back policy pays survival benefits at?',
      optionA: 'End of policy term only',
      optionB: 'Regular intervals during policy term',
      optionC: 'Only on death',
      optionD: 'Only after 10 years',
      correctOption: 'B',
      selectedOption: 'A',
      isCorrect: false,
      marksAwarded: 0,
      explanation:
        'Money-back policies pay survival benefits at regular intervals during the policy term.',
    },
    {
      questionId: 'q-009',
      questionText: 'What is a rider in an insurance policy?',
      optionA: 'A separate standalone policy',
      optionB: 'An add-on benefit attached to base policy',
      optionC: 'A type of premium discount',
      optionD: 'A claim settlement process',
      correctOption: 'B',
      selectedOption: 'B',
      isCorrect: true,
      marksAwarded: 1,
      explanation:
        'A rider is an add-on benefit that can be attached to a base insurance policy for additional coverage.',
    },
    {
      questionId: 'q-010',
      questionText: 'The iC-38 examination is conducted by?',
      optionA: 'LIC of India',
      optionB: 'IRDAI',
      optionC: 'Insurance Institute of India',
      optionD: 'Ministry of Finance',
      correctOption: 'C',
      selectedOption: 'C',
      isCorrect: true,
      marksAwarded: 1,
      explanation:
        'The iC-38 exam is conducted by the Insurance Institute of India on behalf of IRDAI.',
    },
  ],
};
