/**
 * Notifications — `api-contracts/12-notification.md`.
 *
 * Read-and-mark only: notifications are system-generated by src/mocks/notify.js
 * on domain events, and there is no create endpoint in v1.
 *
 * Every endpoint is scoped to the caller. A notification belonging to someone
 * else is a 404, never a 403 — existence is hidden (§3).
 *
 * TEMPORARY DEV SCAFFOLDING. See src/mocks/README.md.
 */

import { db } from "../db.js";
import { authenticate } from "../guard.js";
import { notFound, ok, paginate } from "../respond.js";

/** The wire shape — `recipientId` is internal and never exposed. */
const view = ({ recipientId, ...notification }) => notification;

const mine = (accountId) =>
  db.notifications
    .filter((n) => n.recipientId === accountId)
    .sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt)));

// ── 1. list ────────────────────────────────────────────────────────────────

function listNotifications(request, _params, url) {
  const auth = authenticate(request);
  if (auth.response) return auth.response;

  let rows = mine(auth.account.id);

  const isRead = url.searchParams.get("isRead");
  const type = url.searchParams.get("type");
  if (isRead !== null) rows = rows.filter((n) => String(n.isRead) === isRead);
  if (type) rows = rows.filter((n) => n.type === type);

  const { slice, meta } = paginate(rows, url.searchParams);
  return ok(slice.map(view), meta);
}

// ── 2. unread count ────────────────────────────────────────────────────────

/** Deliberately cheap: the contract says this is safe to poll for a badge. */
function unreadCount(request) {
  const auth = authenticate(request);
  if (auth.response) return auth.response;

  const unread = db.notifications.filter(
    (n) => n.recipientId === auth.account.id && !n.isRead,
  ).length;

  return ok({ unread });
}

// ── 3. mark one read ───────────────────────────────────────────────────────

function markRead(request, { id }) {
  const auth = authenticate(request);
  if (auth.response) return auth.response;

  const notification = db.notifications.find(
    (n) => n.id === id && n.recipientId === auth.account.id,
  );
  // someone else's notification is indistinguishable from a missing one
  if (!notification) return notFound("Notification");

  // idempotent: already-read returns the same shape, keeping the original time
  if (!notification.isRead) {
    notification.isRead = true;
    notification.readAt = new Date().toISOString();
  }

  return ok({
    id: notification.id,
    isRead: notification.isRead,
    readAt: notification.readAt,
  });
}

// ── 4. mark all read ───────────────────────────────────────────────────────

function markAllRead(request) {
  const auth = authenticate(request);
  if (auth.response) return auth.response;

  const now = new Date().toISOString();
  let markedRead = 0;

  for (const notification of db.notifications) {
    if (notification.recipientId !== auth.account.id || notification.isRead) {
      continue;
    }
    notification.isRead = true;
    notification.readAt = now;
    markedRead += 1;
  }

  return ok({ markedRead });
}

export const notificationRoutes = [
  // the literal segments come first so neither can be read as an :id
  {
    method: "GET",
    path: "/me/notifications/unread-count",
    handler: unreadCount,
  },
  { method: "POST", path: "/me/notifications/read-all", handler: markAllRead },
  { method: "GET", path: "/me/notifications", handler: listNotifications },
  { method: "POST", path: "/me/notifications/:id/read", handler: markRead },
];
